GET http://localhost:3001/categories 

###

GET http://localhost:3001/categories/id

###

POST http://localhost:3001/categories 
content-type: application/json

{
    "name": "objegt uusgeh"
}

###

DELETE http://localhost:3001/categories/e8c4de31-8ab0-4c3e-9285-369e34f7d785


###

PUT http://localhost:3001/categories/0a0bcc26-9c4e-442d-8dd3-73361e3a2361
content-type: application/json

{
    "name":"item nemeggrh"
} 

### 
GET http://localhost:3001/articles/37d935c0-fa20-4bed-afd3-d6b9d88898b5